"""Build the Hebrew (RTL) final-project slide deck: slides/toto-final-project-he.pptx

Design: dark navy canvas, orange/blue/green accents, right-to-left layout
(accent bar + titles on the right, charts on the left), KPI tiles, real charts
from slides/charts_he (generated by make_charts_he.py from the live outputs).
Numbers are read from outputs/*.md so the deck matches the latest Flow run.
"""
from __future__ import annotations

import json
import os
import re

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_CONNECTOR, MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.oxml.ns import qn
from pptx.util import Emu, Inches, Pt

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "..")
CH = os.path.join(HERE, "charts_he")
SCREEN = os.path.join(HERE, "screenshot-app.png")
OUT_PATH = os.path.join(HERE, "toto-final-project-he.pptx")

DARK = RGBColor(0x0F, 0x17, 0x2A)
CARD = RGBColor(0x1E, 0x29, 0x3B)
CARD_LINE = RGBColor(0x33, 0x41, 0x55)
BLUE = RGBColor(0x3B, 0x82, 0xF6)
ORANGE = RGBColor(0xF9, 0x73, 0x16)
GREEN = RGBColor(0x10, 0xB9, 0x81)
RED = RGBColor(0xEF, 0x44, 0x44)
PURPLE = RGBColor(0x8B, 0x5C, 0xF6)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
GRAY = RGBColor(0xCB, 0xD5, 0xE1)
MUTED = RGBColor(0x94, 0xA3, 0xB8)
FONT = "Arial"

# ------------------------------------------------------------------ live numbers
def _read(p):
    p = os.path.join(BASE, p)
    return open(p, encoding="utf-8").read() if os.path.exists(p) else ""

eval_md = _read("outputs/evaluation_report.md")
metrics = {}
for line in eval_md.splitlines():
    m = re.match(r"\|\s*(RandomForestClassifier|GradientBoostingClassifier)([^|]*)\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|", line)
    if m:
        metrics[m.group(1)] = dict(selected="✅" in m.group(2), acc=float(m.group(3)), prec=float(m.group(4)),
                                   rec=float(m.group(5)), f1=float(m.group(6)), auc=float(m.group(7)))
best_name = next((k for k, v in metrics.items() if v["selected"]), "GradientBoostingClassifier")
best = metrics.get(best_name, dict(acc=0.787, prec=0.791, rec=0.617, f1=0.693, auc=0.875))
other_name = next((k for k in metrics if k != best_name), "RandomForestClassifier")
other = metrics.get(other_name, dict(acc=0.787, prec=0.787, rec=0.622, f1=0.695, auc=0.871))
mtrain = re.search(r"Train set: (\d+).*Test set: (\d+)", eval_md)
n_train, n_test = (int(mtrain.group(1)), int(mtrain.group(2))) if mtrain else (77438, 40129)
try:
    contract = json.load(open(os.path.join(BASE, "outputs", "dataset_contract.json"), encoding="utf-8"))
    n_rows = contract.get("row_count", 117567)
    n_feats = len(contract.get("feature_columns", [])) or 25
    cancel_rate = float(contract.get("class_balance", {}).get("1", 0.373)) * 100
except Exception:
    n_rows, n_feats, cancel_rate = 117567, 25, 37.3
BEST_HE = "Gradient Boosting" if best_name.startswith("Gradient") else "Random Forest"
OTHER_HE = "Random Forest" if BEST_HE == "Gradient Boosting" else "Gradient Boosting"

# ------------------------------------------------------------------ pptx helpers
prs = Presentation()
prs.slide_width, prs.slide_height = Inches(13.333), Inches(7.5)
SW, SH = prs.slide_width, prs.slide_height
BLANK = prs.slide_layouts[6]


def rtl(paragraph, align=PP_ALIGN.RIGHT):
    """Mark a paragraph as right-to-left and right-aligned."""
    pPr = paragraph._p.get_or_add_pPr()
    pPr.set("rtl", "1")
    paragraph.alignment = align


def add_bg(slide, color=DARK):
    bg = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SW, SH)
    bg.fill.solid(); bg.fill.fore_color.rgb = color
    bg.line.fill.background(); bg.shadow.inherit = False
    slide.shapes._spTree.remove(bg._element)
    slide.shapes._spTree.insert(2, bg._element)


def add_text(slide, l, t, w, h, text, size=18, bold=False, color=WHITE, align=PP_ALIGN.RIGHT,
             font=FONT, spacing=1.15, anchor=None):
    box = slide.shapes.add_textbox(l, t, w, h)
    tf = box.text_frame; tf.word_wrap = True
    if anchor: tf.vertical_anchor = anchor
    for i, line in enumerate(text.split("\n")):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        r = p.add_run(); r.text = line
        r.font.size = Pt(size); r.font.bold = bold; r.font.color.rgb = color; r.font.name = font
        p.line_spacing = spacing
        rtl(p, align)
    return box


def add_bullets(slide, l, t, w, h, items, size=16, color=GRAY, bullet="◀", bullet_color=ORANGE, gap=10):
    """RTL bullet list. Each item may be 'bold part|rest' to emphasize a lead-in."""
    box = slide.shapes.add_textbox(l, t, w, h)
    tf = box.text_frame; tf.word_wrap = True
    for i, item in enumerate(items):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        rb = p.add_run(); rb.text = bullet + "  "
        rb.font.size = Pt(size - 4); rb.font.color.rgb = bullet_color; rb.font.name = FONT
        if "|" in item:
            lead, rest = item.split("|", 1)
            r1 = p.add_run(); r1.text = lead
            r1.font.size = Pt(size); r1.font.bold = True; r1.font.color.rgb = WHITE; r1.font.name = FONT
            r2 = p.add_run(); r2.text = rest
            r2.font.size = Pt(size); r2.font.color.rgb = color; r2.font.name = FONT
        else:
            r = p.add_run(); r.text = item
            r.font.size = Pt(size); r.font.color.rgb = color; r.font.name = FONT
        p.line_spacing = 1.25; p.space_after = Pt(gap)
        rtl(p)
    return box


def add_accent_bar(slide, color=ORANGE):
    bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, SW - Inches(0.15), 0, Inches(0.15), SH)
    bar.fill.solid(); bar.fill.fore_color.rgb = color
    bar.line.fill.background(); bar.shadow.inherit = False


def add_header(slide, title, subtitle=None, accent=ORANGE):
    add_accent_bar(slide, accent)
    add_text(slide, Inches(0.6), Inches(0.35), Inches(12.1), Inches(0.9), title, size=32, bold=True)
    if subtitle:
        add_text(slide, Inches(0.6), Inches(1.1), Inches(12.1), Inches(0.5), subtitle, size=15, color=MUTED)
    # thin underline
    ln = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(9.7), Inches(1.32 if not subtitle else 1.62), Inches(3.0), Emu(28000))
    ln.fill.solid(); ln.fill.fore_color.rgb = accent; ln.line.fill.background(); ln.shadow.inherit = False


def add_footer(slide, n):
    add_text(slide, Inches(0.5), Inches(7.02), Inches(3), Inches(0.35), f"{n}", size=11, color=MUTED, align=PP_ALIGN.LEFT)
    add_text(slide, Inches(6.5), Inches(7.02), Inches(6.2), Inches(0.35),
             "Toto — פרויקט גמר · ניר וייצמן", size=11, color=MUTED)


def card(slide, l, t, w, h, color=CARD, line=CARD_LINE, radius=None):
    c = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, l, t, w, h)
    c.fill.solid(); c.fill.fore_color.rgb = color
    c.line.color.rgb = line; c.line.width = Pt(1.25); c.shadow.inherit = False
    if radius is not None:
        c.adjustments[0] = radius
    return c


def img_card(slide, path, l, t, w, h, caption=None):
    """Image inside a card; the image is fitted (aspect-preserved) into w x h and
    the card shrinks to hug it, so there is never dead space below the picture."""
    from PIL import Image
    iw, ih = Image.open(path).size
    pad = Inches(0.12)
    cap_h = Inches(0.4) if caption else 0
    avail_w, avail_h = w - 2 * pad, h - 2 * pad
    scale = min(avail_w / iw, avail_h / ih)
    pw, ph = int(iw * scale), int(ih * scale)
    card_w, card_h = pw + 2 * pad, ph + 2 * pad + cap_h
    cl = l + int((w - card_w) / 2)
    card(slide, cl, t, card_w, card_h, radius=0.04)
    slide.shapes.add_picture(path, cl + pad, t + pad, width=pw, height=ph)
    if caption:
        add_text(slide, cl, t + pad + ph, card_w, Inches(0.4), caption, size=11, color=MUTED, align=PP_ALIGN.CENTER)
    return card_h


def kpi(slide, l, t, w, h, value, label, color, size=34, label_size=13):
    c = card(slide, l, t, w, h, radius=0.08)
    c.line.color.rgb = color; c.line.width = Pt(2)
    add_text(slide, l, t + Inches(0.15), w, Inches(0.9), value, size=size, bold=True, color=color, align=PP_ALIGN.CENTER)
    add_text(slide, l, t + h - Inches(0.6), w, Inches(0.5), label, size=label_size, color=GRAY, align=PP_ALIGN.CENTER)


def arrow_left(slide, x_from, x_to, y, color=WHITE):
    conn = slide.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, x_from, y, x_to, y)
    conn.line.color.rgb = color; conn.line.width = Pt(2.5)
    ln = conn.line._get_or_add_ln()
    tail = ln.makeelement(qn("a:tailEnd"), {"type": "triangle", "w": "lg", "len": "lg"})
    ln.append(tail)


slide_no = 0
def new_slide(title=None, subtitle=None, accent=ORANGE):
    global slide_no
    slide_no += 1
    s = prs.slides.add_slide(BLANK)
    add_bg(s)
    if title:
        add_header(s, title, subtitle, accent)
    add_footer(s, slide_no)
    return s


# =================================================================== 1. Title
s = new_slide()
add_accent_bar(s, BLUE)
# decorative circles
for (cx, cy, r, col) in [(Inches(1.4), Inches(5.6), Inches(2.6), CARD), (Inches(11.4), Inches(1.0), Inches(1.6), CARD)]:
    o = s.shapes.add_shape(MSO_SHAPE.OVAL, cx - r, cy - r, 2 * r, 2 * r)
    o.fill.solid(); o.fill.fore_color.rgb = col; o.line.fill.background(); o.shadow.inherit = False
    s.shapes._spTree.remove(o._element); s.shapes._spTree.insert(3, o._element)
add_text(s, Inches(1), Inches(1.7), Inches(11.5), Inches(0.6), "פרויקט גמר · קורס פיתוח AI ושיתוף פעולה", size=16, color=ORANGE, bold=True)
add_text(s, Inches(1), Inches(2.25), Inches(11.5), Inches(1.0), "Toto — סימולציה של צוות מוצר AI תעשייתי", size=40, bold=True)
add_text(s, Inches(1), Inches(3.35), Inches(11.5), Inches(1.0),
         "מערכת CrewAI דו-צוותית שהופכת נתוני הזמנות מלון גולמיים למודל חיזוי ביטולים — מקצה לקצה", size=19, color=GRAY)
add_text(s, Inches(1), Inches(4.7), Inches(11.5), Inches(0.5), "ניר וייצמן  |  אוגוסט 2026", size=16, color=MUTED)
# tech chips
chips = ["CrewAI Flow", "Claude (Anthropic)", "Python 3.12", "Scikit-Learn", "Streamlit", "GitHub"]
x = Inches(12.5)
for chip in chips:
    w = Inches(0.105 * len(chip) + 0.45)
    x -= w
    c = card(s, x, Inches(5.7), w, Inches(0.42), color=CARD, line=CARD_LINE, radius=0.5)
    add_text(s, x, Inches(5.72), w, Inches(0.4), chip, size=12, color=GRAY, align=PP_ALIGN.CENTER)
    x -= Inches(0.15)

# =================================================================== 2. Agenda
s = new_slide("סדר היום", accent=BLUE)
agenda = [
    "הרקע העסקי והבעיה", "הרעיון — מי זה Toto", "ארכיטקטורה: 2 צוותים + Flow", "הדאטהסט ותובנות ה-EDA",
    "צוות 1 — אנליסט נתונים (4 סוכנים)", "שער הולידציה של ה-Flow", "צוות 2 — מדען נתונים (3 סוכנים)",
    "תוצאות המודל ו-Model Card", "אפליקציית Streamlit ודמו", "שחזור, טכנולוגיה וסיכום",
]
half = (len(agenda) + 1) // 2
for col, items in enumerate([agenda[:half], agenda[half:]]):
    l = Inches(6.9) if col == 0 else Inches(0.7)
    for i, item in enumerate(items):
        n = i + 1 + col * half
        t = Inches(1.9) + i * Inches(0.95)
        c = card(s, l, t, Inches(5.7), Inches(0.75), radius=0.15)
        badge = s.shapes.add_shape(MSO_SHAPE.OVAL, l + Inches(5.7) - Inches(0.7), t + Inches(0.12), Inches(0.5), Inches(0.5))
        badge.fill.solid(); badge.fill.fore_color.rgb = [BLUE, ORANGE, GREEN][n % 3]; badge.line.fill.background(); badge.shadow.inherit = False
        add_text(s, l + Inches(5.0), t + Inches(0.14), Inches(0.5), Inches(0.5), str(n), size=14, bold=True, align=PP_ALIGN.CENTER)
        add_text(s, l + Inches(0.2), t + Inches(0.15), Inches(4.7), Inches(0.5), item, size=16)

# =================================================================== 3. Business background
s = new_slide("הרקע העסקי", "למה ביטולי הזמנות הם בעיה של כסף אמיתי")
add_bullets(s, Inches(6.4), Inches(1.9), Inches(6.3), Inches(4.8), [
    "רשת מלונאות|  מפעילה כמה מלונות (בהשראת תפעול אמיתי: מלון בוטיק באילת ומלון עירוני בתל אביב).",
    "כל ביטול = הפסד:|  חדרים שלא נמכרו, כוח אדם מיותר, תחזיות שגויות ומדיניות Overbooking שנשענת על תחושת בטן.",
    "ההנהלה צריכה שתי זוויות:|  תיאורית — \"מה קורה בהזמנות שלנו?\" וחיזויית — \"אילו הזמנות צפויות להתבטל?\"",
    "המטרה:|  צינור AI מקצה לקצה, ניתן לשחזור, שקולט נתונים גולמיים, מפיק תובנות ומנבא סיכון ביטול כבר ברגע ההזמנה.",
], size=16)
img_card(s, f"{CH}/class_balance.png", Inches(0.7), Inches(1.9), Inches(5.3), Inches(4.7),
         caption=f"{n_rows:,} הזמנות אמיתיות · פורטוגל 2015–2017 · {cancel_rate:.1f}% בוטלו")

# =================================================================== 4. The concept
s = new_slide("הרעיון — \"Toto\"", "מסוכן אישי יומיומי לצוות מוצר מדומה", accent=GREEN)
add_bullets(s, Inches(5.2), Inches(1.9), Inches(7.5), Inches(4.8), [
    "Toto הוא סוכן AI אמיתי|  שפועל יום-יום: מעקב משפטי, בנקאות, לוגיסטיקה משפחתית ותפעול מלונות.",
    "אותה פילוסופיה בקנה מידה תעשייתי:|  סוכנים מתמחים, לכל אחד תפקיד אחד ברור, שמשתפים פעולה דרך העברות מוגדרות.",
    "צוות 1 (אנליסט)|  משקף איך Toto קולט מידע גולמי ומבולגן והופך אותו לתובנה מובנית ואמינה.",
    "צוות 2 (מדען נתונים)|  משקף איך Toto הופך תובנה לכלי תומך החלטה — חיזוי חי, לא רק דוח.",
    "ה-Flow אוכף שערי ולידציה|  בין הצוותים — בדיוק כמו ש-Toto לא פועל על מידע לא מאומת.",
], size=16)
# principle cards on the left
for i, (icon, title, desc, col) in enumerate([
    ("🎯", "תפקיד אחד לסוכן", "כל סוכן עושה דבר אחד — ועושה אותו טוב", BLUE),
    ("🔒", "כלים דטרמיניסטיים", "pandas ו-sklearn עושים את העבודה, ה-LLM מנהל", ORANGE),
    ("🚧", "אין העברה ללא ולידציה", "חוזה נתונים נבדק לפני שצוות 2 מתחיל", GREEN),
]):
    t = Inches(1.9) + i * Inches(1.55)
    c = card(s, Inches(0.7), t, Inches(4.2), Inches(1.35), radius=0.1)
    c.line.color.rgb = col
    add_text(s, Inches(0.85), t + Inches(0.12), Inches(3.9), Inches(0.5), f"{icon}  {title}", size=16, bold=True, color=col)
    add_text(s, Inches(0.85), t + Inches(0.62), Inches(3.9), Inches(0.6), desc, size=13, color=GRAY)

# =================================================================== 5. Architecture
s = new_slide("ארכיטקטורה ברמה גבוהה", "שני צוותים, Flow אחד, שני שערי ולידציה — הכל אוטומטי", accent=BLUE)

def arch_box(l, t, w, h, title, lines, color):
    b = card(s, l, t, w, h, radius=0.06); b.line.color.rgb = color; b.line.width = Pt(2.5)
    add_text(s, l + Inches(0.15), t + Inches(0.15), w - Inches(0.3), Inches(0.9), title, size=18, bold=True, color=color)
    add_bullets(s, l + Inches(0.15), t + Inches(1.05), w - Inches(0.3), h - Inches(1.1), lines, size=13, bullet="•", bullet_color=color, gap=4)

arch_box(Inches(9.0), Inches(2.0), Inches(3.7), Inches(3.4), "צוות 1 · אנליסט נתונים",
         ["Ingestion — פרופיל הנתונים", "Cleaning — clean_data.csv", "EDA — eda_report.html", "Insights + Contract"], BLUE)
arch_box(Inches(4.85), Inches(2.4), Inches(3.6), Inches(2.6), "CrewAI Flow",
         ["שער ולידציה: חוזה ↔ נתונים", "נכשל בחן על דליפה/אי-התאמה", "העברה אוטומטית + לוג ריצה"], ORANGE)
arch_box(Inches(0.65), Inches(2.0), Inches(3.7), Inches(3.4), "צוות 2 · מדען נתונים",
         ["Contract Validator", "Feature Engineer — features.csv", "ML Engineer — 2 מודלים", "model.pkl + model card"], GREEN)
arrow_left(s, Inches(9.0), Inches(8.5), Inches(3.7))
arrow_left(s, Inches(4.85), Inches(4.35), Inches(3.7))
c = card(s, Inches(0.65), Inches(5.75), Inches(12.05), Inches(0.9), radius=0.2)
add_text(s, Inches(0.8), Inches(5.83), Inches(11.8), Inches(0.75),
         "raw csv  →  clean_data.csv  →  eda_report.html  →  insights.md  →  dataset_contract.json  ✅  →  features.csv  →  model.pkl  →  evaluation_report.md  →  model_card.md  ✅  →  Streamlit",
         size=12, color=GRAY, align=PP_ALIGN.CENTER, font="Consolas")

# =================================================================== 6. Numbers
s = new_slide("הפרויקט במספרים", accent=GREEN)
tiles = [
    (f"{n_rows:,}", "הזמנות אמיתיות אחרי ניקוי", BLUE),
    (f"{cancel_rate:.1f}%", "שיעור ביטולים כולל", RED),
    ("7", "סוכני AI מתמחים (4 + 3)", ORANGE),
    (f"{best['auc']:.3f}", f"ROC-AUC · {BEST_HE}", GREEN),
    (f"{n_feats}", "פיצ'רים מאושרים בחוזה", PURPLE),
    ("2", "שערי ולידציה ב-Flow", ORANGE),
    (f"{n_test:,}", "הזמנות בסט המבחן (2017)", BLUE),
    ("0", "עמודות דליפה במודל", GREEN),
]
for i, (v, lbl, col) in enumerate(tiles):
    r, cidx = divmod(i, 4)
    l = Inches(12.7) - (cidx + 1) * Inches(3.0) + Inches(0.1)
    t = Inches(1.9) + r * Inches(2.35)
    kpi(s, l, t, Inches(2.8), Inches(2.0), v, lbl, col)

# =================================================================== 7. Dataset
s = new_slide("הדאטהסט", "Hotel Booking Demand — נתונים אמיתיים, בעיה אמיתית")
add_bullets(s, Inches(6.6), Inches(1.9), Inches(6.1), Inches(4.8), [
    "119,390 הזמנות אמיתיות|  משני מלונות בפורטוגל (Resort + City), 2015–2017. אחרי ניקוי: " + f"{n_rows:,}.",
    "משתנה מטרה:|  is_canceled — " + f"{cancel_rate:.1f}% מההזמנות בוטלו.",
    "פיצול טמפורלי:|  אימון על 2015–2016 (" + f"{n_train:,}" + "), מבחן על 2017 (" + f"{n_test:,}" + ") — מדמה חיזוי אמיתי קדימה בזמן.",
    "עמודות דליפה מוצאות במפורש:|  reservation_status, reservation_status_date — נרשמות אחרי שהתוצאה ידועה.",
    "רלוונטיות ישירה:|  ניהול הכנסות במלונאות — אותה בעיה שמנהלי מלונות מתמודדים איתה כל יום.",
], size=15)
img_card(s, f"{CH}/bookings_by_month.png", Inches(0.7), Inches(1.9), Inches(5.6), Inches(4.7),
         caption="עונתיות ברורה — שיא קיץ ביולי–אוגוסט")

# =================================================================== 8. Crew 1
s = new_slide("צוות 1 — אנליסט נתונים (4 סוכנים)", "מנתונים גולמיים לתובנות ולחוזה נתונים פורמלי", accent=BLUE)
agents1 = [
    ("Data Ingestion Specialist", "טוען את הקובץ הגולמי ומפיק פרופיל: צורה, טיפוסים, ערכים חסרים.", BLUE),
    ("Data Cleaning Engineer", "מנקה בפרוצדורה דטרמיניסטית ומתועדת → clean_data.csv (1,823 שורות הוסרו).", ORANGE),
    ("EDA Analyst", "מחשב שיעורי ביטול, ADR, מדינות מקור, תמהיל ערוצים → eda_report.html.", GREEN),
    ("Insights & Contract Writer", "כותב insights.md עסקי ומייצר dataset_contract.json שמגדיר לצוות 2 מה מותר.", PURPLE),
]
for i, (name, desc, col) in enumerate(agents1):
    t = Inches(1.9) + i * Inches(1.15)
    c = card(s, Inches(6.5), t, Inches(6.2), Inches(1.0), radius=0.1); c.line.color.rgb = col
    add_text(s, Inches(6.65), t + Inches(0.08), Inches(5.9), Inches(0.4), f"{i+1}. {name}", size=15, bold=True, color=col)
    add_text(s, Inches(6.65), t + Inches(0.48), Inches(5.9), Inches(0.5), desc, size=12, color=GRAY)
img_card(s, f"{CH}/cancel_by_hotel.png", Inches(0.7), Inches(1.9), Inches(5.5), Inches(4.6),
         caption="המלון העירוני מבטל הרבה יותר מהמלון הנופש")

# =================================================================== 9. Insights
s = new_slide("תובנות עסקיות מרכזיות", "מה הנתונים אומרים להנהלת המלון", accent=GREEN)
add_bullets(s, Inches(6.4), Inches(1.9), Inches(6.3), Inches(4.9), [
    "המלון העירוני מבטל 41.8%|  לעומת 28.1% במלון הנופש — סיכון גבוה בכ-50%. דורש חיץ Overbooking ומדיניות פיקדון מחמירה.",
    "פיקדון \"ללא החזר\" מבטל כמעט תמיד|  — פרדוקס שמצביע על הזמנות קבוצתיות/מסחריות ספקולטיביות. ממצא שדורש חקירה תפעולית.",
    "קבוצות מבטלות 62%|  מההזמנות, לעומת 15% בערוץ הישיר ו-19% בעסקי — הערוץ הוא מנבא חזק.",
    "OTA שולטות ב-~68%|  מההזמנות (אונליין + אופליין) — עמלות של 15–20%. כל נקודת אחוז לערוץ הישיר = רווח.",
    "104.6 ימים|  זמן הזמנה ממוצע מראש — חלון גדול לפעולה מונעת על הזמנות בסיכון.",
], size=14)
img_card(s, f"{CH}/cancel_by_segment.png", Inches(0.7), Inches(1.9), Inches(5.5), Inches(3.5))
add_text(s, Inches(0.7), Inches(5.42), Inches(5.5), Inches(0.35), "שיעור ביטולים לפי סוג פיקדון", size=12, color=MUTED, align=PP_ALIGN.CENTER)
for i, (v, lbl, col) in enumerate([("99.4%", "ללא החזר (12%)", RED), ("28.6%", "ללא פיקדון (88%)", BLUE), ("22.2%", "ניתן להחזר", GREEN)]):
    kpi(s, Inches(0.7) + i * Inches(1.85), Inches(5.78), Inches(1.75), Inches(1.05), v, lbl, col, size=20, label_size=11)

# =================================================================== 10. Flow gate
s = new_slide("CrewAI Flow — שער הולידציה", "ההעברה בין הצוותים היא לא \"קובץ עובר\" — היא חוזה שנאכף")
add_bullets(s, Inches(6.5), Inches(1.9), Inches(6.2), Inches(3.0), [
    "אוטומציה מלאה:|  צוות 1 → שער → צוות 2 → שער סופי. אין העברת קבצים ידנית.",
    "נכשל בחן:|  FlowValidationError ברור, הריצה נעצרת לפני שמבזבזים קריאת LLM על נתונים שבורים.",
    "לוג ריצה:|  כל שלב נרשם ל-outputs/flow_run_log.json עם חותמת זמן וסטטוס.",
], size=15)
# gate checks card
c = card(s, Inches(6.5), Inches(4.75), Inches(6.2), Inches(2.0), radius=0.08); c.line.color.rgb = ORANGE
add_text(s, Inches(6.65), Inches(4.8), Inches(5.9), Inches(0.4), "מה השער בודק לפני שצוות 2 מתחיל", size=14, bold=True, color=ORANGE)
add_bullets(s, Inches(6.65), Inches(5.2), Inches(5.9), Inches(1.5), [
    "כל 4 הפלטים של צוות 1 קיימים", "עמודת המטרה קיימת בנתונים", "החוזה מצהיר על פיצ'רים (לא ריק) וכולם קיימים ב-CSV",
    "אף עמודת דליפה לא הוכרזה כפיצ'ר", "מספר השורות בחוזה = מספר השורות בפועל",
], size=12, bullet="✓", bullet_color=GREEN, gap=2)
# terminal-style log on left
c = card(s, Inches(0.7), Inches(1.9), Inches(5.5), Inches(4.85), color=RGBColor(0x0B, 0x12, 0x20), radius=0.05)
log_lines = [
    ("[crew1_analyst] started", GRAY), ("[crew1_analyst] completed", GREEN),
    ("[validation_gate] passed —", GREEN),
    (f"  dataset_contract.json matches clean_data.csv", GRAY),
    (f"  ({n_rows} rows, {n_feats} declared feature columns", GRAY),
    ("  all present, leakage columns not declared)", GRAY),
    ("[crew2_scientist] started", GRAY), ("[crew2_scientist] completed", GREEN),
    ("[final_validation] passed — All artifacts present", GREEN),
    ("✅ Flow completed successfully.", WHITE),
    ("", GRAY),
    ("--- negative test (contract lists a leakage col) ---", ORANGE),
    ("[validation_gate] failed — Contract declares", RED),
    ("  leakage columns as features: ['reservation_status']", RED),
    ("FlowValidationError → Crew 2 never started", RED),
]
box = s.shapes.add_textbox(Inches(0.85), Inches(2.0), Inches(5.2), Inches(4.7))
tf = box.text_frame; tf.word_wrap = True
for i, (txt, col) in enumerate(log_lines):
    p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
    r = p.add_run(); r.text = txt; r.font.size = Pt(11); r.font.name = "Menlo"; r.font.color.rgb = col
    p.alignment = PP_ALIGN.LEFT; p.space_after = Pt(3)

# =================================================================== 11. Crew 2
s = new_slide("צוות 2 — מדען נתונים (3 סוכנים)", "מחוזה מאומת למודל מתועד", accent=GREEN)
agents2 = [
    ("Contract Validator", "קורא את dataset_contract.json ומאמת מול clean_data.csv: מטרה, פיצ'רים מוצהרים, דליפה, מספר שורות.", GREEN),
    ("Feature Engineer", f"בונה features.csv רק מ-{n_feats} העמודות שהחוזה אישר. arrival_date_year נשמר כמפתח פיצול בלבד — לא כפיצ'ר.", BLUE),
    ("ML Engineer", "מאמן Random Forest ו-Gradient Boosting בפייפליין אחיד (StandardScaler + One-Hot), בוחר לפי ROC-AUC, כותב דוח ו-Model Card.", ORANGE),
]
for i, (name, desc, col) in enumerate(agents2):
    t = Inches(1.9) + i * Inches(1.5)
    c = card(s, Inches(6.5), t, Inches(6.2), Inches(1.3), radius=0.1); c.line.color.rgb = col
    add_text(s, Inches(6.65), t + Inches(0.1), Inches(5.9), Inches(0.4), f"{i+1}. {name}", size=15, bold=True, color=col)
    add_text(s, Inches(6.65), t + Inches(0.5), Inches(5.9), Inches(0.8), desc, size=12, color=GRAY)
img_card(s, f"{CH}/lead_time_dist.png", Inches(0.7), Inches(1.9), Inches(5.5), Inches(4.6),
         caption="ככל שמזמינים מוקדם יותר — הסיכוי לביטול גדל")

# =================================================================== 12. Model results
s = new_slide("תוצאות המודל", "השוואה הוגנת על סט מבחן שהמודל מעולם לא ראה (2017)")
img_card(s, f"{CH}/model_comparison.png", Inches(0.7), Inches(1.9), Inches(7.6), Inches(4.85))
add_bullets(s, Inches(8.5), Inches(1.9), Inches(4.2), Inches(3.2), [
    f"{BEST_HE} נבחר|  — ROC-AUC {best['auc']:.3f}, F1 {best['f1']:.3f}.",
    f"{OTHER_HE}:|  ROC-AUC {other['auc']:.3f}, F1 {other['f1']:.3f} — הפרש קטן, שני המודלים יציבים.",
    "פיצול טמפורלי|  (2015–16 → 2017): אין \"הצצה לעתיד\".",
    "בלי דליפה:|  reservation_status, assigned_room_type ומזהי agent/company הוצאו.",
], size=13)
for i, (v, lbl, col) in enumerate([(f"{best['acc']*100:.1f}%", "דיוק", BLUE), (f"{best['prec']*100:.1f}%", "Precision", GREEN),
                                    (f"{best['rec']*100:.1f}%", "Recall", ORANGE)]):
    l = Inches(12.7) - (i + 1) * Inches(1.42) + Inches(0.06)
    kpi(s, l, Inches(5.3), Inches(1.32), Inches(1.4), v, lbl, col, size=22, label_size=12)

# =================================================================== 13. Model card
s = new_slide("Model Card — AI אחראי", "מה המודל נועד לעשות, מה לא, ומה המגבלות שלו", accent=ORANGE)
cols = [
    ("🎯 מטרה", ["תמיכה בהחלטות Overbooking ומדיניות פיקדון", "ניקוד סיכון מצרפי לתכנון תפעולי", "לא לדחות/להעניש אורח בודד"], BLUE),
    ("⚠️ מגבלות", [f"Recall {best['rec']*100:.0f}% — כשליש מהביטולים לא נתפסים", "נתוני פורטוגל 2015–17 — לא בהכרח מכליל לשווקים אחרים", "לא מכיר זעזועים חיצוניים (מגפה, מלחמה)"], ORANGE),
    ("🛡️ אתיקה", ["country ו-market_segment הם פרוקסי גס — לא לפרופיל אורחים", "אין שימוש במזהים אישיים", "החיזוי הסתברותי — נדרש שיקול דעת אנושי לפני פעולה"], GREEN),
]
for i, (title, items, col) in enumerate(cols):
    l = Inches(12.7) - (i + 1) * Inches(4.0) + Inches(0.05)
    c = card(s, l, Inches(1.9), Inches(3.85), Inches(4.8), radius=0.06); c.line.color.rgb = col; c.line.width = Pt(2)
    add_text(s, l + Inches(0.15), Inches(2.0), Inches(3.55), Inches(0.5), title, size=18, bold=True, color=col)
    add_bullets(s, l + Inches(0.15), Inches(2.6), Inches(3.55), Inches(4.0), items, size=13, bullet="•", bullet_color=col, gap=8)

# =================================================================== 14. Streamlit
s = new_slide("אפליקציית Streamlit", "ממשק אחד שמריץ את ה-Flow ומציג את כל התוצרים", accent=GREEN)
add_bullets(s, Inches(8.4), Inches(1.9), Inches(4.3), Inches(4.8), [
    "Overview|  — הסבר הארכיטקטורה ושאלת העסק.",
    "Run Flow|  — כפתור אחד מריץ את כל ה-Flow עם קריאות LLM אמיתיות ומציג את לוג הריצה.",
    "EDA & Insights|  — גרפים חיים מ-clean_data.csv, insights.md, דוח EDA והחוזה.",
    "Model Results|  — דוח הערכה, Model Card, וחיזוי חי: מזינים פרטי הזמנה ומקבלים הסתברות ביטול.",
], size=14)
img_card(s, SCREEN, Inches(0.7), Inches(1.9), Inches(7.5), Inches(4.85))

# =================================================================== 15. Reproducibility
s = new_slide("שחזור, איכות וטכנולוגיה", accent=BLUE)
items_l = [
    ("🔁 שחזור מלא", "הרצת הכלים הדטרמיניסטיים על הנתונים הגולמיים מחזירה בדיוק את אותן מטריקות (random_state=42, פיצול טמפורלי קבוע)."),
    ("🧪 שער שנבדק גם בשלילה", "החוזה נבדק מול נתונים אמיתיים: חוזה ריק, עמודה חסרה או עמודת דליפה — כולם עוצרים את ה-Flow."),
    ("🔐 סודות מחוץ ל-Git", "מפתח ה-API ב-.env (ב-.gitignore); המודל נבחר דרך משתנה סביבה."),
    ("📦 כל התוצרים בריפו", "חוזה, EDA, insights, מודל, דוח הערכה, Model Card ולוג הריצה — כולם מגובים ב-GitHub."),
]
for i, (title, desc) in enumerate(items_l):
    t = Inches(1.7) + i * Inches(1.25)
    c = card(s, Inches(4.9), t, Inches(7.8), Inches(1.1), radius=0.08)
    add_text(s, Inches(5.05), t + Inches(0.08), Inches(7.5), Inches(0.4), title, size=15, bold=True, color=[BLUE, ORANGE, GREEN, PURPLE][i])
    add_text(s, Inches(5.05), t + Inches(0.48), Inches(7.5), Inches(0.6), desc, size=12, color=GRAY)
c = card(s, Inches(0.7), Inches(1.7), Inches(4.0), Inches(4.85), radius=0.06); c.line.color.rgb = BLUE
add_text(s, Inches(0.85), Inches(1.8), Inches(3.7), Inches(0.5), "🛠️ Tech Stack", size=18, bold=True, color=BLUE)
add_bullets(s, Inches(0.85), Inches(2.4), Inches(3.7), Inches(4.0), [
    "CrewAI (Agents, Tasks, Flow)", "Claude Sonnet 4.6 · Anthropic", "Python 3.12", "Pandas · Scikit-Learn", "Matplotlib · Seaborn",
    "Streamlit", "GitHub — github.com/nirwaizman/toto-final-project",
], size=13, bullet="•", bullet_color=BLUE, gap=6)

# =================================================================== 16. Conclusion
s = new_slide("סיכום", accent=GREEN)
add_bullets(s, Inches(0.7), Inches(1.9), Inches(12.0), Inches(3.6), [
    "Flow דו-צוותי עובד ומשוחזר|  — 7 סוכנים מתמחים, 2 שערי ולידציה, 8 תוצרים מתועדים.",
    "פותר בעיה מלונאית אמיתית|  — חיזוי סיכון ביטול ברגע ההזמנה לתמיכה בהחלטות הכנסה.",
    "משמעת מודלינג:|  פיצול טמפורלי, אפס דליפה, השוואת מודלים שקופה, Model Card עם מגבלות ואתיקה.",
    "אותה פילוסופיה כמו Toto:|  סוכנים מתמחים, העברות מאומתות, תמיכה בהחלטה — לא אוטומציה עיוורת.",
], size=17)
c = card(s, Inches(2.2), Inches(5.35), Inches(8.9), Inches(1.2), radius=0.3); c.line.color.rgb = GREEN; c.line.width = Pt(2)
add_text(s, Inches(2.3), Inches(5.45), Inches(8.7), Inches(0.5), "תודה!  שאלות?", size=24, bold=True, align=PP_ALIGN.CENTER)
add_text(s, Inches(2.3), Inches(5.95), Inches(8.7), Inches(0.5), "github.com/nirwaizman/toto-final-project", size=14, color=GRAY, align=PP_ALIGN.CENTER, font="Consolas")

prs.save(OUT_PATH)
print(f"Saved {OUT_PATH} — {len(prs.slides._sldIdLst)} slides")
